admins/urls.py
from django.urls import path
from .import views
app_name='admins'


urlpatterns=[
   path('login/',views.login,name='login'),
   path('home/',views.home,name='home'),
   path('master/',views.master,name='master'),
   path('add_products/',views.add_products,name='add_products'),
   path('order_his/',views.order_his,name='order_his'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('product_catelogue/',views.product_catelogue,name='product_catelogue'),
   path('recent_orders/',views.recent_orders,name='recent_orders'),
   path('update_stock/<int:pid>',views.update_stock,name='update_stock'),
   path('edit_profile/',views.edit_profile,name='edit_profile'),
   path('logout/',views.logout,name='logout'),
   path('sample/',views.sample,name='sample'),
   path('add_category/',views.add_category,name='add_category'),
   path('add_type/',views.add_type,name='add_type'),
   path('add_style/',views.add_style,name='add_style'),
   path('get_type/',views.get_type,name='get_type'),
   path('get_addproduct/',views.get_addproduct,name='get_addproduct')


  
  
]

customer/urls.py
from django.urls import path
from .import views
app_name='customer'

urlpatterns=[
   path('home/',views.home,name='home'),
   path('master/',views.master,name='master'),
   path('account/',views.account,name='account'),
   path('cart/',views.cart,name='cart'),
   path('logout/',views.logout,name='logout'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('orders/',views.orders,name='orders'),
   path('product/list',views.list_products,name='list_products'),
   path('editprofile/',views.editprofile,name='editprofile'),
   path('product_detail/<int:pid>',views.product_detail,name='product_detail'),
   path('delete_item/<int:pid>',views.delete_item,name='delete_item'),
   path('cmia/',views.cmia,name='cmia'),

   path('order_product/',views.order_product,name='order_product'),
   path('updatepayment/',views.updatepayment,name='updatepayment'),



   path('search/',views.search,name='search'),
   # path('change_qty',views.change_qty,name="change_qty"),

   # path('orderpayment/',views.orderpayment,name='orderpayment'),
   # path('update_payment/',views.update_payment,name='update_payment'),
   # path('pay/',views.pay,name='pay'),
   # path('update/',views.update,name='update'),

   


]

home/urls.py
from django.urls import path
from .import views
app_name='home'

urlpatterns=[
    path('homepage/',views.homepage,name='homepage'),
    path('customerlogin/',views.customerlogin,name='customerlogin'),
    # path('view_product/',views.view_product,name='view_product'),
    path('master/',views.master,name='master'),
    path('cus_registration/',views.cus_registration,name='cus_registration'),
    path('sel_registration/',views.sel_registration,name='sel_registration'),
    path('mia/',views.mia,name='mia'),
    path('email_exist/',views.email_exist,name='email_exist'),
    path('view_product/<int:pid>',views.view_product,name='view_product'),
    path('product/list',views.list_products,name='list_products'),
    path('search/',views.search,name='search'),
    # path('diamond/',views.diamond,name='diamond'),
    # path('hoops_huggies/',views.hoops_huggies,name='hoops_huggies'),
    # path('jhumkas/',views.jhumkas,name='jhumkas'),
    # path('stud/',views.stud,name='stud'),
    # path('mangalsutra/',views.mangalsutra,name='mangalsutra'),
    # path('traditional/',views.traditional,name='traditional'),
    # path('bib/',views.bib,name='bib'),
    # path('alljewellery/',views.alljewellery,name='alljewellery'),
    # path('earrings/',views.earrings,name='earrings'),
    # path('rings/',views.rings,name='rings'),
    # path('necklaces/',views.necklaces,name='necklaces'),
                  
                  
]

jewelleryerp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('admins/',include('admins.urls')),
    path('customer/',include('customer.urls')),
    path('seller/',include('seller.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from .import views
app_name='seller'


urlpatterns=[
     # path('add_product/',views.add_product,name='add_product'),
     # path('home/',views.home,name='home'),
     # path('edit_profile/',views.edit_profile,name='edit_profile'),
     # path('master/',views.master,name='master'),
     # path('change_pass/',views.change_pass,name='change_pass'),
     # path('order_his/',views.order_his,name='order_his'),
     # path('product_catelogue/',views.product_catelogue,name='product_catelogue'),
     # path('recent_orders/',views.recent_orders,name='recent_orders'),
     # path('update_stock/',views.update_stock,name='update_stock'),
]

home/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):

    image=models.ImageField(upload_to='customer')
    name=models.CharField(max_length=100)
    gender=models.CharField(max_length=100)
    phone_no=models.CharField(max_length=25)
    e_mail=models.CharField(max_length=200)
    address=models.CharField(max_length=1000)
    password=models.CharField(max_length=25)
    
    
    
    class Meta:
        db_table='customer' 


class Seller(models.Model):
    # seller_name=models.CharField(max_length=100)
    company_name=models.CharField(max_length=200)
    address=models.CharField(max_length=500)
    mobile=models.CharField(max_length=20)
    e_mail=models.CharField(max_length=100)
    company_logo=models.ImageField(upload_to='seller/')
    bank_name=models.CharField(max_length=150)
    acc_name=models.CharField(max_length=150)
    accc_no=models.BigIntegerField()
    ifsc=models.CharField(max_length=150)
    branch_name=models.CharField(max_length=500)
    Username=models.CharField(max_length=100)
    password=models.CharField(max_length=16)

    class Meta:
        db_table='seller'
 

seller/models.py
from django.db import models

# Create your models here.

home/views.py
import random
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.core.mail import send_mail
from admins.models import Product
from customer.models import Mycart
from home.models import Customer, Seller
from jewelleryerp import settings
from django.db.models import Q


# Create your views here.

# def alljewellery(request):
#     prod_list=Product.objects.all()
#     return render(request,'home_templates/alljewellery.html',{'prod_data':prod_list})
def list_products(request):
    if 'style' in request.GET:
        search_query = request.GET['style']
        print(search_query)
        product_list = Product.objects.filter(style = search_query)

    if 'type' in request.GET:
        
        if 'category' in request.GET:
            product_list = Product.objects.filter(type = request.GET['type'], category = request.GET['category'])
        if 'style' in request.GET:
            product_list = Product.objects.filter(type = request.GET['type'], style = request.GET['style'])
    elif 'category' in request.GET:
        search_query = request.GET['category']
        product_list = Product.objects.filter(category = search_query)

    elif 'items' in request.GET:
        product_list = Product.objects.all()

     
    return render(request,'home_templates/product_list.html',{'data': product_list})
    # return render(request,'home_templates/product_list.html')

def homepage(request):
    return render(request,'home_templates/homepage.html')

def mia(request):
    return render(request,'home_templates/mia.html')

def view_product(request,pid):
    msg=''
    product = Product.objects.get(id=pid)
    if request.method =='POST':
        quantity=request.POST['qty']
        product_exist=Mycart.objects.filter(product=pid,customer=request.session['customer']).exists()
        print(product_exist)
        if not product_exist:
            item = Mycart(customer_id = request.session['customer'],product_id = pid,quantity = quantity)
            item.save()
        else:  
            msg = 'Item already added'
    return render(request,'home_templates/view_product.html',{'product_details':product,'msg':msg})




def customerlogin(request):
    msg=''
    if request.method=="POST":
        c_mail=request.POST['email']
        c_pass=request.POST['password']
        try:
            customer=Customer.objects.get(e_mail=c_mail,password=c_pass)
            request.session['customer']=customer.id
            return redirect('customer:home')
        except:
            msg="Invalid emailid or password!!!!"
    return render(request,'home_templates/customerlogin.html',{'msg':msg})

def master(request,id):
    data=Product.objects.filter().values('category').distinct()
   
    return render(request,'home_templates/master.html',{'prod_data':data})

def view_product(request,pid):

    # to show products
    msg=''
    product = Product.objects.get(id=pid)

    # code to add product in to cart
    # if request.method =='POST':
    #     quantity=request.POST['qty']
    #     product_exist=Mycart.objects.filter(product=pid,customer=request.session['customer']).exists()
    #     print(product_exist)
    #     if not product_exist:
    #         item = Mycart(customer_id = request.session['customer'],product_id = pid,quantity = quantity)
    #         item.save()
    #     else:  
    #         msg = 'Item already added'
            
    # context = {
    #     'product_details':product,
    #     'msg':msg
    # }
    return render (request,'home_templates/view_product.html',{'product_details':product})


    # return render(request,'home_templates/view_product.html')



def cus_registration(request):
    if request.method=='POST':
        cimage=request.FILES['c_img']
        cname=request.POST['c_name']
        cgender=request.POST['c_gender']
        cphone=request.POST['c_phone']
        cemail=request.POST['c_email']
        caddress=request.POST['c_address']
        cpassword=request.POST['c_password']
        new_customer=Customer(
            image=cimage,
            name=cname,
            gender=cgender,
            phone_no=cphone,
            e_mail=cemail,
            address=caddress,
            password=cpassword 
        )
        new_customer.save()
     



    return render(request,'home_templates/cus_registration.html')

def sel_registration(request):
    if request.method=='POST':
        # r_name=request.POST['s_name']
        r_com=request.POST['s_com_name']
        r_address=request.POST['s_address']
        r_mobileno=request.POST['s_mobileno']
        r_email=request.POST['s_email']
        r_logo=request.FILES['s_logo']
        r_bname=request.POST['s_bname']
        r_holder=request.POST['s_holder']
        r_accno=request.POST['s_acnumber']
        r_ifsc=request.POST['s_ifsc']
        r_branch=request.POST['s_branch']
        r_username=random.randint(1111,9999)
        r_password='sel-'+ r_com.lower()+str(r_username)
        message='Hello your username is'+str(r_username)+'add temporary password is'+r_password
        new_seller=Seller(
            company_name=r_com,
            address=r_address,
            mobile=r_mobileno,
            e_mail=r_email,
            company_logo=r_logo,
            bank_name=r_bname,
            acc_name=r_holder,
            accc_no=r_accno,
            ifsc=r_ifsc,
            branch_name=r_branch,
            Username=r_username,
            password=r_password
        )
       
        new_seller.save()
        

    return render(request,'home_templates/sel_registration.html')



# def master(request):
#     return render(request,'home_templates/master.html')


def email_exist(request):
    # email is a variable to store value of emailid given in customer registration
    email=request.POST['email']
# e_mail is the name give for the table in database ,checks this value is equal to the value is input box of email if exits or not this value
# is passed to status and then given to registration page to display
    status=Customer.objects.filter(e_mail=email).exists()
    print(status)
    return JsonResponse({'status':status})

def search(request):
    products = []
    count = 0

    if request.method == 'GET':
        print('in get method')
        searched = request.GET.get('search')
        print(searched)
        if searched:
            products = Product.objects.filter(Q(category__icontains=searched) | Q(p_name__icontains=searched))

            print(products)
            count = products.count()            
    context = {
        'result': products,
        'count':count
    }
    return render(request, 'home_templates/search.html', context)

seller/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
# def add_product(request):
#     return render(request,'sel_templates/add_product.html')

# def home(request):
#     return render(request,'sel_templates/home.html')

# def edit_profile(request):
#     return render(request,'sel_templates/edit_profile.html')

# def master(request):
#     return render(request,'sel_templates/master.html')

# def change_pass(request):
#     return render(request,'sel_templates/change_pass.html')

# def order_his(request):
#     return render(request,'sel_templates/order_his.html')

# def product_catelogue(request):
#     return render(request,'sel_templates/product_catelogue.html')

# def recent_orders(request):
#     return render(request,'sel_templates/recent_orders.html')

# def update_stock(request):
#     return render(request,'sel_templates/update_stock.html')

seller/templates/sel_templates/add_product.html
{% extends 'sel_templates/master.html' %}
{% load static %}
{% block content %}
<style>
.ttb{
    padding:50px;
}
</style>
<div>
    <h1 class="hadd">ADD PRODUCT</h1>
</div>
<div class="ttb">
    <table class="tb">

        <tr>
            <td><label for="">Product Name</label></td>
        </tr>
        <tr>
            <td><input type="text" placeholder="" name="s_pname"></td>
        </tr>
        <tr>
            <td><label for="">Product number</label></td>

        </tr>
        <tr>
            <td><input type="text" name="s_pid"></td>
        <tr>
            <td><label for="">Description</label></td>
        </tr>
        <tr>
            <td><textarea name="s_desc" id="" cols="30" rows="10"></textarea></td>
        </tr>

        <tr>
            <td><label for="">Product Stock</label></td>
        </tr>
        <tr>
            <td><input type="text" placeholder="" name="s_pstock"></td>
        </tr>


        <tr>
            <td><label for="">Product price</label></td>
        </tr>
        <tr>
            <td><input type="text" name="s_pprice"></td>
        </tr>
        <tr>
            <td><label for="myfile">Product image</label>
            </td>
        </tr>
        <tr>
            <td><input type="file" id="myfile" name="s_pimg"><br><br></td>
        </tr>
        <tr>

            <td><input type="submit" name="s_submit" value="submit"></td>
        </tr>


    </table>
</div>

{% endblock %}

seller/templates/sel_templates/change_pass.html
{% extends 'sel_templates/master.html' %}

{% load static %}
{% block content %}
<style>
    #ddiv{
    padding-left:50px;
    background-color: #c7c7c7;
}
</style>

<div id="headd">
    <h1 class="hh">CHANGE PASSWORD</h1>

    <div class="container">

        <div class="row">
            <div class="col-sm-4">

                <div id="ddiv">
                    <label class="lbl">Current Password</label>
                <div class="form-group_pass_show">
                    <input type="password" value="" class="form-control" placeholder="Current Password">
                </div>
                <label>New Password</label>
                <div class="form-group_pass_show">
                    <input type="password" value="" class="form-control" placeholder="New Password">
                </div>
                <label>Confirm Password</label>
                <div class="form-group_pass_show">
                    <input type="password" value="" class="form-control" placeholder="Confirm Password">
                </div>
                <div>
                    <a href="{% url 'customer:home' %}">
                        <input id="btn" type="button" value="SUBMIT"></a>
                        <a href="{% url 'customer:change_pass' %}">
                        <input id="btn" type="button" value="CANCEL"></a>
                </div>
                </div>

            </div>
        </div>
    </div>

<!-- js code 
$(document).ready(function(){
    $('.pass_show').append('<span class="ptxt">Show</span>');  
    });
      
    
    $(document).on('click','.pass_show .ptxt', function(){ 
    
    $(this).text($(this).text() == "Show" ? "Hide" : "Show"); 
    
    $(this).prev().attr('type', function(index, attr){return attr == 'password' ? 'text' : 'password'; }); 
    
    });   -->

{% endblock %}

seller/templates/sel_templates/edit_profile.html
{% extends 'sel_templates/master.html' %}
{% load static %}
{% block content %}
<!-- <!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> -->


        <title>Edit Seller</title>
   
    <style>
        .pro{
            text-align: center;
        }
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: rgb(178, 178, 178);
        }

        * {
            box-sizing: border-box;
        }

        /* Add padding to containers */
        .container {
            padding: 16px;
            background-color: white;
        }

        /* Full-width input fields */
        input[type=text],
        input[type=password] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }

        input[type=text]:focus,
        input[type=password]:focus {
            background-color: #ddd;
            outline: none;
        }

        /* Overwrite default styles of hr */
        hr {
            border: 1px solid #f1f1f1;
            margin-bottom: 25px;
        }

        /* Set a style for the submit button */
        .registerbtn {
            background-color: #1d8f09;
            color: white;
            padding: 16px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .registerbtn:hover {
            opacity: 1;
            background-color: rgb(4, 86, 25);
        }

        /* Add a blue text color to links */
        a {
            color: dodgerblue;
        }

        /* Set a grey background color and center the text of the "sign in" section */
        /* .signin {
            background-color: #f1f1f1;
            text-align: center;
        } */
    </style>

    <form action="">
        <div></div>
        <div class="container">
            <h1 class="pro">Edit Profile</h1>
            <p>Please fill in this form to create an account.</p>
            <hr>
            Upload image</td> <td><input type="file" name="s_img" id=""><br><br>
           
            <label for="name"><b>Seller Name:</b></label><br>
            <input type="text" size="50" placeholder="" name="s_name" required>
            <br><br>

            <label for="name"><b>Company Name:</b></label><br>
            <input type="text" size="50" placeholder="" name="s_com_name"required>
            <br><br>


            <label for="name"><b>Address:</b></label><br>
            <input type="text" size="50" name="s_address"required>
            <br><br>

            <label for="name"><b>Mobile:</b></label><br>
            <input type="text" size="50" name="s_mobileno"required>
            <br><br>

            

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="s_email" id="email" required>

            <h2>BANK DETAILS</h2>

            <label for="bank_name"><b>Bank name</b></label>
            <input type="text" placeholder="Enter bank name" name="s_bname" id="bname" required>

            <label for="holder"><b>Account holder name</b></label>
            <input type="password" placeholder="" name="s_holder" id="holder" required>

                <label for=""><b>Account number</b></label>
                <input type="text" name="s_acnumber" id=""required>

                <label for=""><b>IFSC</b></label>
                <input type="text" name="s_ifsc" id=""required>

                <label for=""><b>Branch</b></label>
                <input type="text" name="s_branch" id=""required>

            <hr>
            <!-- <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p> -->

           <a href="{% url 'seller:home' %}"> <button type="submit" class="registerbtn">Update</button></a>
           <a href="{% url 'seller:home' %}"> <button type="submit" class="registerbtn">Cancel?</button></a>
        </div>

        <!-- <div class="container signin">
            <p>Already have an account? <a href="{% url 'home:sellerlogin' %}">Sign in</a>.</p>
        </div> -->
    </form>
    {% endblock %}
<!-- 
</body>

</html> -->

seller/templates/sel_templates/home.html
{% extends 'sel_templates/master.html' %}
{% load static %}
{% block content %}

<style>
   #welh{
        text-align: center;
    }
    input.right {
        float: right;
      }
      .right:hover{

        display: flex;
        color: red;
        background-color: black;
      }
      .containerdiv{
        padding: 20px;
        background-color: rgb(105, 132, 128);
        /* margin-left: 20px; */
      }
</style>

<form action="">

    <div><h1 id="welh">WELCOME</h1 id="welh"></div>
       
    <div class="containerdiv">
        
        
        
        
        <div>
          
           <a href="{% url 'seller:edit_profile' %}"> <input type="button" value="Edit Profile" class="right"></a><br>
        </div>
        <div class="img">
            <label for="">Image</label>
        </div><br>
        <div class="container-name">
            <label for="">Name</label>
            <span>type name</span>
        </div><br>
        <div class="Company_name">
            <label for="">Company name</label>
            <span>type Company_name</span>
        </div><br>
        <div>
            <label for="">Address</label>
        </div><br>
        <div>
            <label for="">Phone</label>
        </div><div><br>
            <label for="">E-mail</label>
        </div><br>
    <div>
        <label for="">Bank Name</label>
    </div><br>
    <div>
        <label for="">Account holder name</label>
    </div><br>
        <div>
            <label for="">Account number</label>
        </div><br>
        <div>
            <label for="">IFSC</label>
        </div><br>
        <div>
            <label for="">Branch</label>
        </div>
        <br>
    <div>
        <label for="">Username</label>
    </div><br>
    </div>
</form>
<!-- {% endblock %} <form action=""method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <tr>
        <h1>SELLER PROFILE</h1>
        name :
        <h1>{{data.seller_name}}</h1>
        image :
        <img src="{{data.company_logo.url}}" alt="">
        <br>
        company name:{{data.company_name}}<br>
        account number:{{data.s_acc_no}}<br>

        IFSC CODE:{{data.ifsc}}<br>
        BRANCH:{{data.s_branch_name}}<br>
        ACCOUNT HOLDER NAME:{{data.acc_name}}<br>
        PHONE NUMBER:{{data.mobile}} <br>
        E-MAIL:{{data.e_mail}} <br>
        ADDRESS:{{data.address}} <br>
        USERNAME:{{data.Username}} <br> -->

seller/templates/sel_templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TANISHQ</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- <link rel="stylesheet" href="{% static 'css/earrings.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/masters.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_product.css' %}">
    <link rel="stylesheet" href="{% static 'css/change_pass.css' %}">
    <link rel="stylesheet" href="{% static 'css/order_his.css' %}">
    <link rel="stylesheet" href="{% static 'css/update_stock.css' %}">

    

</head>

<body>
    <header>


        <div class="maindiv">
            <div class="tablediv">

                <table width="100%">
                    <tr>
                        <td align="left">
                            <img class="tanishqimg" src="{% static 'images/Tanishq.jpg' %}" ,width="1px" ,height="1px">
                        </td>
                        <td colspan="2" align="center">
                           
                                <input type="text" id="fname" name="firstname" placeholder="Search....">
                           
                        </td>
                       
                       
                       
                    </tr>
                </table>


                <div class="items">
                    <table id="itemslabel" width="100%px">

                        <tr>
                            <td>---------</td>
                            <td>
                                <a href="{% url 'home:homepage' %}"> <label id="alllabel">ALL JEWELLERY</label></a>

                            </td>
                            <td>

                                <a href="{% url 'home:earrings' %}"><label id="alllabel">EARRINGS</label></a>
                            </td>
                            <!-- <td>
                                <a href="{% url 'home:rings' %}"><label id="alllabel">RINGS</label></a>
                            </td> -->
                            <td>
                                <a href="{% url 'home:necklaces' %}"><label id="alllabel">NECKLACES</label></a>
                            </td>
                            <td>
                                <a href="#"><label id="alllabel">GOLD</label></a>
                            </td>
                            <td>
                                <a href="#"> <label id="alllabel">DIAMOND</label></a>
                            </td>
                            <td>
                                <a href="#"><label id="alllabel">MIA</label></a>
                            </td>
                            <td>
                                <a href="#"><label id="alllabel">COLLECTIONS</label></a>
                            </td>

                        </tr>
                    </table>

                </div>
            </div>
        </div>

    </header>


    {% block content %}

    {% endblock %}





</body>

</html>

seller/templates/sel_templates/order_his.html
{% extends 'sel_templates/master.html' %}

{% load static %}
{% block content %}
<div id="container">
    <div class="containermy">
        <h1 class="myorders">ORDER HISTORY</h1>
    </div> 
    <div class="content">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">slno.</th>
                    <th scope="col">Product Image</th>
                    <th scope="col">Name</th>
                    <th scope="col">Delivered on</th>
                    <th scope="col">Customer Name</th>

                </tr>

            </thead>
        </table>
        nkbcsjc <br>
        vvs
        dc
        <br><br><br><br><br>
    </div>
</div>


{% endblock %}

seller/templates/sel_templates/product_catelogue.html
{% extends 'sel_templates/master.html' %}
{% load static %}
{% block content %}
<style>
    .container{
        width: 100px;
        height: 200px;

    }
    .card-img-top{
        width: 70px;
        height: 70px;

    }
    .product{
        display: grid;
        grid-template-columns: auto auto auto auto;
    }
</style>
</head>

<body>
<form action="" method="POST" enctype="multipart/form-data">
    <div class="container">
        <div class="seller">
            <h1>PRODUCT CATELOGUE</h1>
        </div>
        <div class="product">
            {% for product in data %}

        <div class="card" style="width: 18rem;">
            <img src="{{product.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{product_details.product_name}}</h5>
                <p class="card-text">{{product.Product_price}}</p>
                <p class="card-text">{{product.description}}</p>
                <input type="button" value="update stock"><a href="#" class="btn btn-primary"></a>
            </div>
        </div>
        
            {% endfor %}
        </div>
        
    </div>
</form>
{% endblock%}

seller/templates/sel_templates/recent_orders.html
{% extends 'sel_templates/master.html' %}

{% load static %}
{% block content %}
<div>
    <div class="containermy">
<h1 class="myorders">RECENT ORDERS</h1>
    </div>
</div>
<div class="content">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Slno.</th>
                <th scope="col">Product Image</th>
                <th scope="col">Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Customer Name</th>
                <th scope="col">Customer Address</th>
                
            </tr>

        </thead>
    </table>
</div>



{% endblock %}