admins/urls.py
from django.urls import path
from .import views
app_name='admins'


urlpatterns=[
   path('login/',views.login,name='login'),
   path('home/',views.home,name='home'),
   path('master/',views.master,name='master'),
   path('add_products/',views.add_products,name='add_products'),
   path('order_his/',views.order_his,name='order_his'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('product_catelogue/',views.product_catelogue,name='product_catelogue'),
   path('recent_orders/',views.recent_orders,name='recent_orders'),
   path('update_stock/<int:pid>',views.update_stock,name='update_stock'),
   path('edit_profile/',views.edit_profile,name='edit_profile'),
   path('logout/',views.logout,name='logout'),
   path('sample/',views.sample,name='sample'),
   path('add_category/',views.add_category,name='add_category'),
   path('add_type/',views.add_type,name='add_type'),
   path('add_style/',views.add_style,name='add_style'),
   path('get_type/',views.get_type,name='get_type'),
   path('get_addproduct/',views.get_addproduct,name='get_addproduct')


  
  
]

customer/urls.py
from django.urls import path
from .import views
app_name='customer'

urlpatterns=[
   path('home/',views.home,name='home'),
   path('master/',views.master,name='master'),
   path('account/',views.account,name='account'),
   path('cart/',views.cart,name='cart'),
   path('logout/',views.logout,name='logout'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('orders/',views.orders,name='orders'),
   path('product/list',views.list_products,name='list_products'),
   path('editprofile/',views.editprofile,name='editprofile'),
   path('product_detail/<int:pid>',views.product_detail,name='product_detail'),
   path('delete_item/<int:pid>',views.delete_item,name='delete_item'),
   path('cmia/',views.cmia,name='cmia'),

   path('order_product/',views.order_product,name='order_product'),
   path('updatepayment/',views.updatepayment,name='updatepayment'),



   path('search/',views.search,name='search'),
   # path('change_qty',views.change_qty,name="change_qty"),

   # path('orderpayment/',views.orderpayment,name='orderpayment'),
   # path('update_payment/',views.update_payment,name='update_payment'),
   # path('pay/',views.pay,name='pay'),
   # path('update/',views.update,name='update'),

   


]

home/urls.py
from django.urls import path
from .import views
app_name='home'

urlpatterns=[
    path('homepage/',views.homepage,name='homepage'),
    path('customerlogin/',views.customerlogin,name='customerlogin'),
    # path('view_product/',views.view_product,name='view_product'),
    path('master/',views.master,name='master'),
    path('cus_registration/',views.cus_registration,name='cus_registration'),
    path('sel_registration/',views.sel_registration,name='sel_registration'),
    path('mia/',views.mia,name='mia'),
    path('email_exist/',views.email_exist,name='email_exist'),
    path('view_product/<int:pid>',views.view_product,name='view_product'),
    path('product/list',views.list_products,name='list_products'),
    path('search/',views.search,name='search'),
    # path('diamond/',views.diamond,name='diamond'),
    # path('hoops_huggies/',views.hoops_huggies,name='hoops_huggies'),
    # path('jhumkas/',views.jhumkas,name='jhumkas'),
    # path('stud/',views.stud,name='stud'),
    # path('mangalsutra/',views.mangalsutra,name='mangalsutra'),
    # path('traditional/',views.traditional,name='traditional'),
    # path('bib/',views.bib,name='bib'),
    # path('alljewellery/',views.alljewellery,name='alljewellery'),
    # path('earrings/',views.earrings,name='earrings'),
    # path('rings/',views.rings,name='rings'),
    # path('necklaces/',views.necklaces,name='necklaces'),
                  
                  
]

jewelleryerp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('admins/',include('admins.urls')),
    path('customer/',include('customer.urls')),
    path('seller/',include('seller.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):

    image=models.ImageField(upload_to='customer')
    name=models.CharField(max_length=100)
    gender=models.CharField(max_length=100)
    phone_no=models.CharField(max_length=25)
    e_mail=models.CharField(max_length=200)
    address=models.CharField(max_length=1000)
    password=models.CharField(max_length=25)
    
    
    
    class Meta:
        db_table='customer' 


class Seller(models.Model):
    # seller_name=models.CharField(max_length=100)
    company_name=models.CharField(max_length=200)
    address=models.CharField(max_length=500)
    mobile=models.CharField(max_length=20)
    e_mail=models.CharField(max_length=100)
    company_logo=models.ImageField(upload_to='seller/')
    bank_name=models.CharField(max_length=150)
    acc_name=models.CharField(max_length=150)
    accc_no=models.BigIntegerField()
    ifsc=models.CharField(max_length=150)
    branch_name=models.CharField(max_length=500)
    Username=models.CharField(max_length=100)
    password=models.CharField(max_length=16)

    class Meta:
        db_table='seller'
 

home/views.py
import random
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.core.mail import send_mail
from admins.models import Product
from customer.models import Mycart
from home.models import Customer, Seller
from jewelleryerp import settings
from django.db.models import Q


# Create your views here.

# def alljewellery(request):
#     prod_list=Product.objects.all()
#     return render(request,'home_templates/alljewellery.html',{'prod_data':prod_list})
def list_products(request):
    if 'style' in request.GET:
        search_query = request.GET['style']
        print(search_query)
        product_list = Product.objects.filter(style = search_query)

    if 'type' in request.GET:
        
        if 'category' in request.GET:
            product_list = Product.objects.filter(type = request.GET['type'], category = request.GET['category'])
        if 'style' in request.GET:
            product_list = Product.objects.filter(type = request.GET['type'], style = request.GET['style'])
    elif 'category' in request.GET:
        search_query = request.GET['category']
        product_list = Product.objects.filter(category = search_query)

    elif 'items' in request.GET:
        product_list = Product.objects.all()

     
    return render(request,'home_templates/product_list.html',{'data': product_list})
    # return render(request,'home_templates/product_list.html')

def homepage(request):
    return render(request,'home_templates/homepage.html')

def mia(request):
    return render(request,'home_templates/mia.html')

def view_product(request,pid):
    msg=''
    product = Product.objects.get(id=pid)
    if request.method =='POST':
        quantity=request.POST['qty']
        product_exist=Mycart.objects.filter(product=pid,customer=request.session['customer']).exists()
        print(product_exist)
        if not product_exist:
            item = Mycart(customer_id = request.session['customer'],product_id = pid,quantity = quantity)
            item.save()
        else:  
            msg = 'Item already added'
    return render(request,'home_templates/view_product.html',{'product_details':product,'msg':msg})




def customerlogin(request):
    msg=''
    if request.method=="POST":
        c_mail=request.POST['email']
        c_pass=request.POST['password']
        try:
            customer=Customer.objects.get(e_mail=c_mail,password=c_pass)
            request.session['customer']=customer.id
            return redirect('customer:home')
        except:
            msg="Invalid emailid or password!!!!"
    return render(request,'home_templates/customerlogin.html',{'msg':msg})

def master(request,id):
    data=Product.objects.filter().values('category').distinct()
   
    return render(request,'home_templates/master.html',{'prod_data':data})

def view_product(request,pid):

    # to show products
    msg=''
    product = Product.objects.get(id=pid)

    # code to add product in to cart
    # if request.method =='POST':
    #     quantity=request.POST['qty']
    #     product_exist=Mycart.objects.filter(product=pid,customer=request.session['customer']).exists()
    #     print(product_exist)
    #     if not product_exist:
    #         item = Mycart(customer_id = request.session['customer'],product_id = pid,quantity = quantity)
    #         item.save()
    #     else:  
    #         msg = 'Item already added'
            
    # context = {
    #     'product_details':product,
    #     'msg':msg
    # }
    return render (request,'home_templates/view_product.html',{'product_details':product})


    # return render(request,'home_templates/view_product.html')



def cus_registration(request):
    if request.method=='POST':
        cimage=request.FILES['c_img']
        cname=request.POST['c_name']
        cgender=request.POST['c_gender']
        cphone=request.POST['c_phone']
        cemail=request.POST['c_email']
        caddress=request.POST['c_address']
        cpassword=request.POST['c_password']
        new_customer=Customer(
            image=cimage,
            name=cname,
            gender=cgender,
            phone_no=cphone,
            e_mail=cemail,
            address=caddress,
            password=cpassword 
        )
        new_customer.save()
     



    return render(request,'home_templates/cus_registration.html')

def sel_registration(request):
    if request.method=='POST':
        # r_name=request.POST['s_name']
        r_com=request.POST['s_com_name']
        r_address=request.POST['s_address']
        r_mobileno=request.POST['s_mobileno']
        r_email=request.POST['s_email']
        r_logo=request.FILES['s_logo']
        r_bname=request.POST['s_bname']
        r_holder=request.POST['s_holder']
        r_accno=request.POST['s_acnumber']
        r_ifsc=request.POST['s_ifsc']
        r_branch=request.POST['s_branch']
        r_username=random.randint(1111,9999)
        r_password='sel-'+ r_com.lower()+str(r_username)
        message='Hello your username is'+str(r_username)+'add temporary password is'+r_password
        new_seller=Seller(
            company_name=r_com,
            address=r_address,
            mobile=r_mobileno,
            e_mail=r_email,
            company_logo=r_logo,
            bank_name=r_bname,
            acc_name=r_holder,
            accc_no=r_accno,
            ifsc=r_ifsc,
            branch_name=r_branch,
            Username=r_username,
            password=r_password
        )
       
        new_seller.save()
        

    return render(request,'home_templates/sel_registration.html')



# def master(request):
#     return render(request,'home_templates/master.html')


def email_exist(request):
    # email is a variable to store value of emailid given in customer registration
    email=request.POST['email']
# e_mail is the name give for the table in database ,checks this value is equal to the value is input box of email if exits or not this value
# is passed to status and then given to registration page to display
    status=Customer.objects.filter(e_mail=email).exists()
    print(status)
    return JsonResponse({'status':status})

def search(request):
    products = []
    count = 0

    if request.method == 'GET':
        print('in get method')
        searched = request.GET.get('search')
        print(searched)
        if searched:
            products = Product.objects.filter(Q(category__icontains=searched) | Q(p_name__icontains=searched))

            print(products)
            count = products.count()            
    context = {
        'result': products,
        'count':count
    }
    return render(request, 'home_templates/search.html', context)

admins/templates/ad_templates/add_products.html
{% extends 'ad_templates/master.html' %}
{% load static %}
{% block content %}
<style>
    .ttb {
        padding: 50px;
    }

    .nav {
        background-color: rgb(121, 116, 125);
        margin-left: 450px;
        padding: 80px;
        width: 500px;
        height: auto;
    }

    p {
        color: rgb(255, 255, 255);
    }
</style>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="ttb">
        <div>
            <h1 class="hadd">ADD PRODUCT</h1>
        </div>
        <div class="nav">
            <table class="tb">
                <tr>
                    <td><label id="lbl" for="">
                            <p>Product category</p>
                        </label></td>

                </tr>
                <tr>
                    <td>
                        <div class="maindiv">
                            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="category"
                                id="select1">
                                <option selected>select category</option>
                                <option value="Earrings">Earrings</option>
                                <option value="Necklaces">Necklaces</option>
                            </select>
                        </div>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td><label id="lbl" for="">
                            <p>Product type</p>
                        </label></td>
                    </td>
                </tr>
                <tr>
                    <td>
                        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="type"id="select2">
                            <option selected>select type</option>
                             
                            <option value="Gold">Gold</option>
                            <option value="Diamond">Diamond</option>

                           
                        </select>             
                    </td>
                </tr>

                <tr>

                    <td><label id="lbl" for="">
                            <p>Product style</p>
                        </label></td>
                    </td>
                </tr>
                <tr>
                    <td>
                        
                        <!-- <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="style"id="select3">
                            <option selected>select style</option>
                            <option value=""></option>
                        </select>  -->
                        <input type="text" placeholder="" name="style">
                        
                         </select>
                       
                    </td>
                </tr>

                <tr>
                    <td><label id="lbl" for="">
                            <p>Product Name</p>
                        </label></td>
                </tr>
                <tr>

                    <td><input type="text" placeholder="" name="s_pname"></td>
                </tr>
                <tr>
                    <td><label id="lbl" for="">
                            <p>Product number</p>
                        </label></td>

                </tr>
                <tr>
                    <td><input type="text" name="s_pid"></td>
                <tr>
                    <td><label id="lbl" for="">
                            <p>Description</p>
                        </label></td>
                </tr>
                <tr>
                    <td><textarea name="s_pdesc" id="" cols="30" rows="10"></textarea></td>
                </tr>

                <tr>
                    <td><label id="lbl" for="">
                            <p>Product Stock</p>
                        </label></td>
                </tr>
                <tr>
                    <td><input type="text" placeholder="" name="s_pstock"></td>
                </tr>


                <tr>
                    <td><label id="lbl" for="">
                            <p>Product price</p>
                        </label></td>
                </tr>
                <tr>
                    <td><input type="text" name="s_pprice"></td>
                </tr>



                <tr>
                    <td><label id="lbl" for="myfile">
                            <p>Product image</p>
                        </label>
                    </td>
                </tr>
                <tr>
                    <td><input type="file" id="myfile" name="s_pimg"><br><br></td>
                </tr>
                <tr>

                    <td>
                        <!-- <div class="d-flex justify-content-center"> -->

                        <input type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body"
                            value="update">
                        <!-- </div>           -->


                        <!-- <input type="submit" name="s_submit" value="submit"> -->
                    </td>
                </tr>


            </table>
        </div>
    </div>
</form>


<!-- <script>

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()  //passing csrf token in ajax request
            }
        })
        $('#select1').change(function () {
            var selectedValue = $(this).val();
            
            $.ajax({
                url: '{% url "admins:get_type" %}',
                type: 'POST',
                data: { 
                    'selectedValue': selectedValue,
                 },
                success: function (response) {
                    console.log(response.data)
                    // alert(response.data)
                    // $('#select2').html(response.options);

                   data = response.data

                    
                    ptype = ""
                    $('#select2').empty()
                    for (i in data) {
                        ptype += "<option value=" + data[i].id + ">" + data[i].type + "</option>"
                    }
                    $('#select2').append(ptype)
                    console.log(ptype)

                }
            })
        }) -->
        // $('#select2').change(function () {
        //     var selectedValue2 = $(this).val();
            
        //     $.ajax({
        //         url: '{% url "admins:get_addproduct" %}',
        //         type: 'POST',
        //         data: { 
        //             'selectedValue2': selectedValue2,
        //          },
        //         success: function (response) {
        //             console.log(response.datas)
        //             alert(response.data)
        //             $('#select2').html(response.options);

        //            data2 = response.datas

                    
        //             ptype = ""
        //             $('#select3').empty()
        //             for (i in data2) {
        //                 ptype += "<option value=" + data2[i].id + ">" + data2[i].type + "</option>"
        //             }
        //             $('#select3').append(ptype)
        //             console.log(ptype)

        //         }
        //     })
        // })
      
                <!-- });

</script> -->

{% endblock %}

admins/templates/ad_templates/login.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    <style>
        .gradient-custom {
            /* fallback for old browsers */
            background: #f093fb;

            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1));

            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1))
        }

        .login_card {
            padding: 100px;
            display: grid;
            justify-content: center;
        }

        .login_card h2 {
            /* color: rgb(106, 0, 255); */
            text-align: center;
            font-family: Arial, Helvetica, sans-serif;
        }

        .form {
            background-color: rgba(156, 203, 227, 0.335);
            display: flex;
            justify-content: center;
            width: 100%;
            padding: 20px;

        }

        .form input {
            margin: 5px;
            border: none;
            width: 100%;
        }

        form button:hover {
            margin: 5px;
            width: 75%;
            /* border: none; */

            /* text-decoration: none; */
            background-color: rgb(5, 5, 69);
            color: aliceblue;

        }

        .imgwidth {
            width: 10px;
            height: 200px;
        }

        .vh-100 {
            background-color: #7b2043;
            width: 100%;
            height: 100%;
        }

        .carousel-inner,
        .carousel-item.active {
            height: 100vh;
        }

        .carousel-item:nth-child(1) {
            /* background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.jpg'); */
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
        }

        #cus {
            color: beige;
        }

        #cardbd {
            margin-left: 150px;
            padding-left: 150px;
        }

        #forgot {
            color: rgb(9, 9, 9);
        }
        #sign,#email,#pass{
            color: rgb(254, 254, 255);
        }
    </style>
</head>

<body>


    <div class="carousel-inner">

        <div class="carousel-item active">
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
                <div class="d-flex justify-content-center align-items-center h-100">
                    <div class="text-white text-center">
                        <br>
                        <h1 class="mb-3" id="cus">Admin Login</h1>
                        <br><br>


                    </div>


                </div>
            </div>




            <section class="vh-100">
                <div class="container py-5 h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col col-xl-10">
                            <div class="card" style="border-radius: 1rem;">
                                <div class="row g-0">
                                    <!-- <div class="col-md-6 col-lg-5 d-none d-md-block">
                                <img id="imgwidth" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                                  alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                              </div> -->
                                    <div class="col-md-6 col-lg-7 d-flex align-items-center" id="cardbd">
                                        <div class="card-body p-4 p-lg-5 text-black">
                                            <form action="" method="POST" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <br><br><br><br>

                                                <h2 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;"id=sign>Sign into
                                                    your account</h2>
                                                <br><br>
                                                <div class="form-outline mb-4">
                                                    <label class="form-label" for="form2Example17"id="email">Username</label>
                                                    <input type="text" id="form2Example17" name="username"
                                                        class="form-control form-control-lg" />

                                                </div>

                                                <div class="form-outline mb-4">
                                                    <label class="form-label" for="form2Example27"id="pass">Password</label>

                                                    <input type="password" id="form2Example27"
                                                        class="form-control form-control-lg" name="password" />
                                                </div><br>

                                                <div class="pt-1 mb-4">
                                                    <!-- <button class="btn btn-dark btn-lg btn-block"
                                                            type="button">Login</button> -->

                                                            <a href="{% url 'admins:home' %}"><input id="btn" type="submit" value="Login" class="btn btn-dark btn-lg btn-block"></a>
                                                   
                                                    <!-- <a href="{% url 'customer:home' %}"><input type="submit" class="btn btn-dark btn-lg btn-block" name="" id=""value="LOGIN"></a>      -->
                                                </div>

                                                <a class="small text-muted" id="forgot"
                                                    href="{% url 'customer:change_pass' %}">
                                                    <h6><b>Forgot password?</b></h6>
                                                </a>
                                                <p class="mb-5 pb-lg-2" style="color: #080808;">Don't have an account?
                                                    <a href="{% url 'home:cus_registration' %}"
                                                        style="color: #040404;">Register here</a>
                                                </p>
                                                <!-- <a href="#!" class="small text-muted"style="color: #080808;"></a>Terms of use.</a>
                                                    <a href="#!" class="small text-muted" style="color: #080808;"></a>Privacy policy</a> -->
                                                {{msg}}
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>




        </section>
</body>


</html>

admins/templates/ad_templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TANISHQ</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- <link rel="stylesheet" href="{% static 'css/earrings.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/masters.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_product.css' %}">
    <link rel="stylesheet" href="{% static 'css/change_pass.css' %}">
    <link rel="stylesheet" href="{% static 'css/order_his.css' %}">
    <link rel="stylesheet" href="{% static 'css/update_stock.css' %}">


<style>
           input[type=text] {
  width: 130px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
}

/* When the input field gets focus, change its width to 100% */
input[type=text]:focus {
  width: 100%;
}
</style>
</head>

<body>
    <header>


        <div class="maindiv">
            <div class="tablediv">

                <table>
                    <tr>
                        <td align="left">
                            <img class="tanishqimg" src="{% static 'images/Tanishq.jpg' %}" ,width="1px" ,height="1px">
                        </td>
                        <td colspan="2" align="center">

                            <input type="text" name="search" placeholder="Search..">
                  
                        </td>
                       

                    </tr>
                </table>


                <div class="items">
                    <table id="itemslabel" width="100%px">

                        <tr>
                            <td>---------</td>
                            <td>
                                <a href="{% url 'admins:home' %}"><label id="alllabel">Home</label></a>

                            </td>
                            <td>

                                <a href="{% url 'admins:add_products' %}"><label id="alllabel">Add Product</label></a>
                            </td>
                            <td>
                                <a href="{% url 'admins:order_his' %}">
                                    <!-- <label id="alllabel">Order History</label></a> -->
                            </td>
                            <td>
                                <a href="{% url 'admins:change_pass' %}"><label id="alllabel">Change Password</label></a>
                            </td>
                            <td>
                                <a href="{% url 'admins:product_catelogue' %}"><label id="alllabel">Product Catelogue</label></a>
                            </td>
                            <td>
                                <a href="{% url 'admins:recent_orders' %}"> <label id="alllabel">Recent Orders</label></a>
                            </td>
                            <td>
                                <a href="{% url 'admins:product_catelogue' %}"><label id="alllabel">Update Stock</label></a>
                            </td>
                            <td>
                                <a href="{% url 'home:homepage' %}"><label id="alllabel">Logout</label></a>
                            </td>

                        </tr>
                    </table>

                </div>
            </div>
        </div>

    </header>


    {% block content %}

    {% endblock %}





</body>

</html>