customer/urls.py
from django.urls import path
from .import views
app_name='customer'

urlpatterns=[
   path('home/',views.home,name='home'),
   path('master/',views.master,name='master'),
   path('account/',views.account,name='account'),
   path('cart/',views.cart,name='cart'),
   path('logout/',views.logout,name='logout'),
   path('change_pass/',views.change_pass,name='change_pass'),
   path('orders/',views.orders,name='orders'),
   path('product/list',views.list_products,name='list_products'),
   path('editprofile/',views.editprofile,name='editprofile'),
   path('product_detail/<int:pid>',views.product_detail,name='product_detail'),
   path('delete_item/<int:pid>',views.delete_item,name='delete_item'),
   path('cmia/',views.cmia,name='cmia'),

   path('order_product/',views.order_product,name='order_product'),
   path('updatepayment/',views.updatepayment,name='updatepayment'),



   path('search/',views.search,name='search'),
   # path('change_qty',views.change_qty,name="change_qty"),

   # path('orderpayment/',views.orderpayment,name='orderpayment'),
   # path('update_payment/',views.update_payment,name='update_payment'),
   # path('pay/',views.pay,name='pay'),
   # path('update/',views.update,name='update'),

   


]

home/urls.py
from django.urls import path
from .import views
app_name='home'

urlpatterns=[
    path('homepage/',views.homepage,name='homepage'),
    path('customerlogin/',views.customerlogin,name='customerlogin'),
    # path('view_product/',views.view_product,name='view_product'),
    path('master/',views.master,name='master'),
    path('cus_registration/',views.cus_registration,name='cus_registration'),
    path('sel_registration/',views.sel_registration,name='sel_registration'),
    path('mia/',views.mia,name='mia'),
    path('email_exist/',views.email_exist,name='email_exist'),
    path('view_product/<int:pid>',views.view_product,name='view_product'),
    path('product/list',views.list_products,name='list_products'),
    path('search/',views.search,name='search'),
    # path('diamond/',views.diamond,name='diamond'),
    # path('hoops_huggies/',views.hoops_huggies,name='hoops_huggies'),
    # path('jhumkas/',views.jhumkas,name='jhumkas'),
    # path('stud/',views.stud,name='stud'),
    # path('mangalsutra/',views.mangalsutra,name='mangalsutra'),
    # path('traditional/',views.traditional,name='traditional'),
    # path('bib/',views.bib,name='bib'),
    # path('alljewellery/',views.alljewellery,name='alljewellery'),
    # path('earrings/',views.earrings,name='earrings'),
    # path('rings/',views.rings,name='rings'),
    # path('necklaces/',views.necklaces,name='necklaces'),
                  
                  
]

jewelleryerp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('admins/',include('admins.urls')),
    path('customer/',include('customer.urls')),
    path('seller/',include('seller.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from datetime import date

from admins.models import Product
from home.models import Customer

# Create your models here.
class Mycart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    quantity=models.BigIntegerField()
    

class Order(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    amount=models.FloatField()
    status= models.CharField(max_length=20,default="pending")
    provider_order_id = models.CharField(max_length=40)
    payment_id = models.CharField(max_length=36)
    signature_id = models.CharField(max_length=128)

    class Meta:
        db_table = 'order_tb'

class Order_detail(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    productid = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=20,default="pending") #update after payment confirmed
    payment_type = models.CharField(max_length=20)
    order=models.ForeignKey(Order,on_delete=models.CASCADE)


    class Meta:
        db_table = 'order_detail'

home/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):

    image=models.ImageField(upload_to='customer')
    name=models.CharField(max_length=100)
    gender=models.CharField(max_length=100)
    phone_no=models.CharField(max_length=25)
    e_mail=models.CharField(max_length=200)
    address=models.CharField(max_length=1000)
    password=models.CharField(max_length=25)
    
    
    
    class Meta:
        db_table='customer' 


class Seller(models.Model):
    # seller_name=models.CharField(max_length=100)
    company_name=models.CharField(max_length=200)
    address=models.CharField(max_length=500)
    mobile=models.CharField(max_length=20)
    e_mail=models.CharField(max_length=100)
    company_logo=models.ImageField(upload_to='seller/')
    bank_name=models.CharField(max_length=150)
    acc_name=models.CharField(max_length=150)
    accc_no=models.BigIntegerField()
    ifsc=models.CharField(max_length=150)
    branch_name=models.CharField(max_length=500)
    Username=models.CharField(max_length=100)
    password=models.CharField(max_length=16)

    class Meta:
        db_table='seller'
 

customer/views.py
from tabnanny import check
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from admins.models import Product
from customer.models import Mycart, Order, Order_detail
from django.db.models import F
from home.models import Customer
from django.db.models import Q
import razorpay
from jewelleryerp import settings

def delete_item(request,pid):
    print('hhh')
    cart_item=Mycart.objects.get(id=pid)
    print(cart_item.id)
    cart_item.delete()
    return redirect('customer:cart')
# Create your views here.
def home(request):
    return render(request,'cus_templates/home.html')

def logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect('home:homepage')

def master(request):
    return render(request,'cus_templates/master.html')

def account(request):
    account_dt=Customer.objects.get(id=request.session['customer'])
    return render(request,'cus_templates/account.html',{'data':account_dt})
    
def cart(request):
    cartdata=Mycart.objects.filter(customer_id=request.session['customer']).annotate(total=F('product__p_price')*F('quantity'))
    
    grand_total=0
    for i in cartdata:

        grand_total=i.total+grand_total
        request.session['grand']=grand_total
    context={
           'data':cartdata,
            'grandtotal':grand_total
                            }
   
    return render(request,'cus_templates/cart.html',context)

def change_pass(request):
    success_msg = ''
    error_msg = ''  
    if request.method == 'POST':
        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        confirm_pass = request.POST['re_password']
        if new_pass == confirm_pass :
            if len(new_pass) >= 8 :
                customer = Customer.objects.get(id = request.session['customer'])
                if customer.password == old_pass :
                    # customer.password = new_pass
                    # customer.save()
                    Customer.objects.filter(id = request.session['customer']).update( password = new_pass )
                    success_msg = 'password changed successfully'
                else:
                    error_msg = 'old password is incorrect'
            else:
                error_msg = 'passwords should be 8 characters'
        else:
            error_msg = 'passwords doesn\'t match'
    return render(request,'cus_templates/change_pass.html',{'success_msg':success_msg,'error_msg':error_msg})


def list_products(request):
    if 'style' in request.GET:
        search_query = request.GET['style']
        print(search_query)
        product_list = Product.objects.filter(style = search_query)

    if 'type' in request.GET:
        
        if 'category' in request.GET:
            product_list = Product.objects.filter(type = request.GET['type'], category = request.GET['category'])
        if 'style' in request.GET:
            product_list = Product.objects.filter(type = request.GET['type'], style = request.GET['style'])


    elif 'category' in request.GET:
        search_query = request.GET['category']
        product_list = Product.objects.filter(category = search_query)

    elif 'items' in request.GET:
        product_list = Product.objects.all()

     
    return render(request,'cus_templates/product_list.html',{'data':product_list})


def orders(request):
    orders=Order_detail.objects.filter(customer_id=request.session['customer'])
    return render(request,'cus_templates/orders.html',{'orders':orders})


def cmia(request):
    return render(request,'cus_templates/cmia.html')

def editprofile(request):
    account_dt=Customer.objects.get(id=request.session['customer'])
    if request.POST:
        
        e_name=request.POST['name']
        e_gender=request.POST['c_gender']
        e_phone=request.POST['phone']
        e_email=request.POST['email']
        e_address=request.POST['address']
        updt=Customer.objects.filter(id=request.session['customer']).update(
                                                                          
                                                                           name=e_name,
                                                                           gender=e_gender,
                                                                           phone_no=e_phone,
                                                                           e_mail=e_email,
                                                                           address=e_address)
      
        try:
            e_image=request.FILES['img']
            account_dt.image=e_image
            account_dt.save()
        except:
            e_image=None
        return redirect('customer:editprofile')


    return render(request,'cus_templates/editprofile.html',{'data':account_dt})

# **************************************



def product_detail(request,pid):
    msg=''
    product = Product.objects.get(id=pid)
    if request.method =='POST':
        quantity=request.POST['qty']
        product_exist=Mycart.objects.filter(product=pid,customer=request.session['customer']).exists()
        print(product_exist)
        if not product_exist:
            item = Mycart(customer_id = request.session['customer'],product_id = pid,quantity = quantity)
            item.save()
        else:  
            msg = 'Item already added'
            
    return render(request,'cus_templates/product_detail.html',{'product_details':product,'msg':msg})

def order_product(request):

    if request.method == "POST":
  
        
        order_amt=request.POST['totalprice']
        order_currency='INR'
       
        notes={'Shipping address':'Bommsnshslli, Bangalore'}
       
        client=razorpay.Client(auth=(settings.RAZORPAY_KEY_ID,settings.RAZORPAY_KEY_SECRET))
        payment = client.order.create(
             { "amount": float(order_amt)*100, "currency": "INR", "payment_capture": "1",'notes':notes}
         )
        customer=request.session['customer']
        new_order=Order(
            customer_id=customer,
            amount=request.session['grand'],
            provider_order_id=payment['id'],
            status='pending'

        )
        new_order.save()
        request.session['order_id']=new_order.id
    return JsonResponse(payment)

def updatepayment(request):
    # user_id=request.session['customer']
    # Order.objects.filter(id=request.session['oid'],customer_id=user_id, status='pending').update(status="paid")
    # pid=Order.objects.filter(id=request.session['oid'],customer_id=user_id, status='pending')
    # print('hello')
    # print(pid)
   
    # customer_id=request.session['customer']
    # products=Mycart.objects.filter(customer_id=customer_id) 

    # for pro in products:

    #     print(pro.product)

    #     order=Order_detail(customer_id=customer_id,
    #                 productid_id=pro.product,
    #                 price=pro.product.price,
    #                 quantity=pro.qty,
    #                 status="paid",
    #                 payment_type="Razorpay",
    #                 order_id= pid[0].id,
    #     )
    #     order.save()
    #     products.delete()

    # Order_detail.objects.filter(customer_id=customer_id, status='order_pending',order_id=request.session['oid']).update(status='paid')
   

    # return JsonResponse({'resp':"success"})
    if request.method=='POST':
        # amount=request.POST['grandtotal']
        paymentid=request.POST['pid']
        orderid=request.POST['oid']
        sigid=request.POST['sig']
        orderqty=0
        updateorderDetail=Order.objects.filter(provider_order_id=orderid).update(
            payment_id=paymentid,
            signature_id=sigid,
            status='paid'
        )
        order_id=request.session['order_id']
        cartitem=Mycart.objects.filter(customer=request.session['customer'])
        for singleitem in cartitem:
            new_order_details=Order_detail(
                customer_id=singleitem.customer_id,
                productid_id=singleitem.product_id,
                price=singleitem.product.p_price,
                quantity=singleitem.quantity,
                status='paid',
                payment_type='razorpay',
                order_id=order_id,

                )
            new_order_details.save()
            orderqty=int(singleitem.quantity)
            stockUpdate=Product.objects.get(id=singleitem.product_id)
            stockUpdate.p_stock=stockUpdate.p_stock-orderqty
            stockUpdate.save()
            cartitem.delete()
    return JsonResponse({'halo': 'hii'})

def search(request):
    products = []
    count = 0

    if request.method == 'GET':
        print('in get method')
        searched = request.GET.get('search')
        print(searched)
        if searched:
            products = Product.objects.filter(Q(category__icontains=searched) | Q(p_name__icontains=searched))

            print(products)
            count = products.count()            
    context = {
        'result': products,
        'count':count
    }
    return render(request, 'cus_templates/search.html', context)

customer/templates/cus_templates/change_pass.html
{% extends 'cus_templates/master.html' %}

{% load static %}
{% block content %}
<style>
    .row {
        margin-left: 400px
    }

    .mm {
        padding: 30px;
        width: 500px;
        height: 300px;
        background-color: rgb(193, 176, 192);
    }

    .containerdiv {
        width: 1475px;
        background-color: rgb(115, 69, 74);
        height: max-content;
    }
    .h6{
        color: aliceblue;
    }
</style>

<!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
<!------ Include the above in your HEAD tag ---------->
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="headd">

        <div class="containerdiv">
            <h1 class="hh">CHANGE PASSWORD</h1>
            <h6 class="text-success text-center bg-white">{{ success_msg }}</h6>
            <h6 class="text-danger text-center bg-white">{{ error_msg }}</h6>
            <div class="row">
                <!-- <div class="col-md-6 col-lg-5 d-none d-md-block">

                <img src="{% static 'image/kokologo.png' %}"
                
                  alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height:450px;" />
              </div>  -->
                <div class="col-sm-4">

                    <div class="mm">
                        <label class="lbl">Current Password</label>
                        <div class="form-group_pass_show">
                            <input type="password" value="" class="form-control" placeholder="Current Password"
                                name="old_password">
                        </div>
                        <label>New Password</label>
                        <div class="form-group_pass_show">
                            <input type="password" value="" class="form-control" placeholder="New Password"
                                name="new_password">
                        </div>
                        <label>Confirm Password</label>
                        <div class="form-group_pass_show">
                            <input type="password" value="" class="form-control" placeholder="Confirm Password"
                                name="re_password">
                        </div>
                        <br>
                        <!-- <div>
                    <a href="{% url 'customer:home' %}">
                        <input id="btn" type="button" value="SUBMIT"></a>
                        <a href="{% url 'customer:change_pass' %}">
                        <input id="btn" type="button" value="CANCEL"></a>
                </div> -->

                        <button type="submit" class="">Submit</button>

                    </div>
                    <br><br><br><br>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- js code 
$(document).ready(function(){
    $('.pass_show').append('<span class="ptxt">Show</span>');  
    });
      
    
    $(document).on('click','.pass_show .ptxt', function(){ 
    
    $(this).text($(this).text() == "Show" ? "Hide" : "Show"); 
    
    $(this).prev().attr('type', function(index, attr){return attr == 'password' ? 'text' : 'password'; }); 
    
    });   -->

{% endblock %}

customer/templates/cus_templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TANISHQ</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- <link rel="stylesheet" href="{% static 'css/earrings.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/masters.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="{% static 'css/change_pass.css' %}">
    <link rel="stylesheet" href="{% static 'css/orders.css' %}">

    <style>
           input[type=text] {
  width: 130px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
}


input[type=text]:focus {
  width: 100%;
}
 .dropbtn {
            background-color: rgb(37, 17, 92);
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f1f1f1;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #ddd;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        
        .tb22div {
            background-color: rgb(37, 17, 92);
            padding-left: 75px;
        }

        table {
            border-spacing: 40px;
        }

        #mia {
            color: aliceblue;
        }
    </style>

</head>

<body>
    <header>


        <div class="maindiv">
            <div class="tablediv">

                <table width="100%">
                    <tr>
                        <td align="left">
                            <img class="tanishqimg" src="{% static 'images/Tanishq.jpg' %}" ,width="1px" ,height="1px">
                        </td>
                        <td colspan="2" align="center">
                            <form action="{% url 'customer:search' %}" method="get">

                                <input type="text" name="search" placeholder="Search..">
                            </form> 
                  
                        </td>
                        <td><a href="{% url 'customer:home' %}"><label id="mlabel">Home</label></a></td>
                        <td><a href="{% url 'customer:account' %}"><label id="mlabel">Account</label></a></td>
                        <td><a href="{% url 'customer:cart' %}"><label id="mlabel">Cart</label></a></td>
                        
                        <td><a href="{% url 'customer:orders' %}"><label id="mlabel">Orders</label></a></td>
                        <td><a href="{% url 'customer:change_pass' %}"><label id="mlabel">Change password</label></a></td>
                        <td><a href="{% url 'home:homepage' %}"><label id="mlabel">Logout</label></a></td>
                       
                       
                    </tr>
                </table>
            </div>
            
            <div class="tb2div">
                <div class="tb22div">
                    <table width="100%">
                        <tr>
                            <td>

                                <div class="dropdown">
                                    <a href="{% url 'customer:list_products' %}?items=all" id="mia"> <button class="dropbtn">ALL
                                            JEWELLERY</a></button>

                                </div>

                            </td>

                            <td>
                                <div class="dropdown">
                                    <a href="" id="mia"> <button
                                            class="dropbtn">EARRINGS</a></button>
                                    <div class="dropdown-content">
                                        <table>
                                            <tr>
                                                <td>


                                                   <b>STYLE</b> 

                                                    <a href="{% url 'customer:list_products' %}?category=Earrings">All earrings</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Jhumkas">Jhumkas</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Hoops and Huggies">Hoops & huggies</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Stud">Stud</a>

                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </td>

                            <td>
                                <div class="dropdown">
                                    <a href="" id="mia"> <button
                                            class="dropbtn">NECKLACES</a></button>

                                    <div class="dropdown-content">
                                        <b>STYLE</b>
                                        <a href="{% url 'customer:list_products' %}?style=Mangalsutra">Mangalsutra</a>
                                        <a href="{% url 'customer:list_products' %}?style=Bib">Bib</a>
                                        <a href="{% url 'customer:list_products' %}?style=Traditional">Traditional</a>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="dropdown">
                                    <a href="{% url 'customer:cmia' %}" id="mia"> <button
                                            class="dropbtn">MIA</a></button>

                                </div>
                            </td>
                            <td>
                                <div class="dropdown">
                                    <a href=" " id="mia">
                                        <button class="dropbtn">GOLD</a></button>
                                    <div class="dropdown-content">
                                        <table>
                                            <tr>
                                                <td>
                                                    <a href="#"><b>CATEGORY</b></a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&category=Earrings"> Earrings</a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&category=Necklaces"> Necklace </a>
                                                    <a href="#"></a>
                                                </td>
                                                <td>
                                                    <a href="#"><b>EARRINGS</b></a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&style=Jhumkas">Jhumkas</a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&style=Hoops and Huggies">Hoops & huggies</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Stud">Stud</a>


                                                </td>
                                                <td>
                                                    <a href="#"><b>NECKLACE</b></a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&style=Mangalsutra">Mangalsutra</a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&style=Bib">Bib</a>
                                                    <a href="{% url 'customer:list_products' %}?type=Gold&style=Traditional">Traditional</a>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>

                            </td>
                            <td>
                                <div class="dropdown">
                                    <a href="" id="mia"><button
                                            class="dropbtn">DIAMOND</a></button>

                                    <div class="dropdown-content">
                                        <table>
                                            <tr>
                                                <td>
                                                    <label for=""><a href="#"><b>CATEGORY</b></a></label>
                                                    <a href="{% url 'customer:list_products' %}?type=Diamond&category=Earrings"> Earrings</a>
                                                    <a href="{% url 'customer:list_products' %}?type=Diamond&category=Necklaces"> Necklace </a>
                                                </td>

                                            </tr>
                                        </table>
                                    </div>
                                </div>

                            </td>
                            <td>
                                <div class="dropdown">
                                    <button class="dropbtn">COLLECTIONS</a></button>

                                    <div class="dropdown-content">
                                        <table>
                                            <tr>
                                                <td>
                                                    <a href="#"><b>STYLE</b></a>
                                                    <a href="{% url 'customer:list_products' %}?style=Mangalsutra">Mangalsutra</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Bib">Bib</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Traditional">Traditional</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Jhumkas">Jhumkas</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Hoops and Huggies">Hoops & huggies</a>
                                                    <a href="{% url 'customer:list_products' %}?style=Stud">Stud</a>

                                                </td>
                                                <td>
                                                    <a href="#"><b>CATEGORY</b></a>
                                                    <a href="{% url 'customer:list_products' %}?category=Earrings"> Earrings</a>
                                                    <a href="{% url 'customer:list_products' %}?category=Necklaces"> Necklace </a>
                                                    <a href="#"></a>
                                                    <a href="#"></a>
                                                    <a href="#"></a>
                                                    <a href="#"></a>
                                                    <a href="#"></a>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </td>

                        </tr>
                    </table>
                </div>
            </div>


        </div>

    </header>


    {% block content %}

    {% endblock %}





</body>

</html>